import type { Boss } from './types';

export const bosses: Boss[] = [
  { id: 'abyssal-sire', bossName: 'Abyssal Sire', petName: 'Abyssal orphan', dropRate: 2560, image: '/images/projects/pets/abyssal-orphan.png' },
  { id: 'alchemical-hydra', bossName: 'Alchemical Hydra', petName: 'Ikkle hydra', dropRate: 3000, image: '/images/projects/pets/ikkle-hydra.png' },
  { id: 'amoxliatl', bossName: 'Amoxliatl', petName: 'Moxi', dropRate: 3000, image: '/images/projects/pets/moxi.png' },
  { id: 'araxxor', bossName: 'Araxxor', petName: 'Nid', dropRate: 3000, image: '/images/projects/pets/nid.png' },
  { id: 'brutus', bossName: 'Brutus', petName: 'Beef', dropRate: 1000, image: '/images/projects/pets/beef.png' },
  { id: 'callisto', bossName: 'Callisto', petName: 'Callisto cub', dropRate: 1500, image: '/images/projects/pets/callisto-cub.png' },
  { id: 'cerberus', bossName: 'Cerberus', petName: 'Hellpuppy', dropRate: 3000, image: '/images/projects/pets/hellpuppy.png' },
  { id: 'chaos-elemental', bossName: 'Chaos Elemental', petName: 'Pet chaos elemental', dropRate: 300, image: '/images/projects/pets/pet-chaos-elemental.png' },
  { id: 'chambers-of-xeric', bossName: 'Chambers of Xeric', petName: 'Olmlet', dropRate: 5000, image: '/images/projects/pets/olmlet.png' },
  { id: 'commander-zilyana', bossName: 'Commander Zilyana', petName: 'Pet zilyana', dropRate: 5000, image: '/images/projects/pets/pet-zilyana.png' },
  { id: 'corporeal-beast', bossName: 'Corporeal Beast', petName: 'Pet dark core', dropRate: 5000, image: '/images/projects/pets/pet-dark-core.png' },
  { id: 'dagannoth-prime', bossName: 'Dagannoth Prime', petName: 'Pet dagannoth prime', dropRate: 5000, image: '/images/projects/pets/pet-dagannoth-prime.png' },
  { id: 'doom-of-mokhaiotl', bossName: 'Doom of Mokhaiotl', petName: 'Dom', dropRate: 500, image: '/images/projects/pets/dom.png' },
  { id: 'duke-sucellus', bossName: 'Duke Sucellus', petName: 'Baron', dropRate: 2500, image: '/images/projects/pets/baron.png' },
  { id: 'dagannoth-rex', bossName: 'Dagannoth Rex', petName: 'Pet dagannoth rex', dropRate: 5000, image: '/images/projects/pets/pet-dagannoth-rex.png' },
  { id: 'dagannoth-supreme', bossName: 'Dagannoth Supreme', petName: 'Pet dagannoth supreme', dropRate: 5000, image: '/images/projects/pets/pet-dagannoth-supreme.png' },
  { id: 'general-graardor', bossName: 'General Graardor', petName: 'Pet general graardor', dropRate: 5000, image: '/images/projects/pets/pet-general-graardor.png' },
  { id: 'giant-mole', bossName: 'Giant Mole', petName: 'Baby mole', dropRate: 3000, image: '/images/projects/pets/baby-mole.png' },
  { id: 'grotesque-guardians', bossName: 'Grotesque Guardians', petName: 'Noon', dropRate: 3000, image: '/images/projects/pets/noon.png' },
  { id: 'the-hueycoatl', bossName: 'The Hueycoatl', petName: 'Huberte', dropRate: 400, image: '/images/projects/pets/huberte.png' },
  { id: 'kalphite-queen', bossName: 'Kalphite Queen', petName: 'Kalphite princess', dropRate: 3000, image: '/images/projects/pets/kalphite-princess.png' },
  { id: 'king-black-dragon', bossName: 'King Black Dragon', petName: 'Prince black dragon', dropRate: 3000, image: '/images/projects/pets/prince-black-dragon.png' },
  { id: 'kraken', bossName: 'Kraken', petName: 'Pet kraken', dropRate: 3000, image: '/images/projects/pets/pet-kraken.png' },
  { id: 'kreearra', bossName: "Kree'arra", petName: "Pet kree'arra", dropRate: 5000, image: '/images/projects/pets/pet-kreearra.png' },
  { id: 'kril-tsutsaroth', bossName: "K'ril Tsutsaroth", petName: "Pet k'ril tsutsaroth", dropRate: 5000, image: '/images/projects/pets/pet-kril-tsutsaroth.png' },
  { id: 'the-leviathan', bossName: 'The Leviathan', petName: "Lil'viathan", dropRate: 2500, image: '/images/projects/pets/lilviathan.png' },
  { id: 'nex', bossName: 'Nex', petName: 'Nexling', dropRate: 500, image: '/images/projects/pets/nexling.png' },
  { id: 'nightmare', bossName: 'Nightmare', petName: 'Little nightmare', dropRate: 4000, image: '/images/projects/pets/little-nightmare.png' },
  { id: 'phantom-muspah', bossName: 'Phantom Muspah', petName: 'Muphin', dropRate: 2500, image: '/images/projects/pets/muphin.png' },
  { id: 'royal-titans', bossName: 'Royal Titans', petName: 'Bran', dropRate: 3000, image: '/images/projects/pets/bran.png' },
  { id: 'sarachnis', bossName: 'Sarachnis', petName: 'Sraracha', dropRate: 3000, image: '/images/projects/pets/sraracha.png' },
  { id: 'scurrius', bossName: 'Scurrius', petName: 'Scurry', dropRate: 3000, image: '/images/projects/pets/scurry.png' },
  { id: 'shellbane-gryphon', bossName: 'Shellbane Gryphon', petName: 'Gull', dropRate: 3000, image: '/images/projects/pets/gull.png' },
  { id: 'scorpia', bossName: 'Scorpia', petName: "Scorpia's offspring", dropRate: 2016, image: '/images/projects/pets/scorpias-offspring.png' },
  { id: 'skotizo', bossName: 'Skotizo', petName: 'Skotos', dropRate: 65, image: '/images/projects/pets/skotos.png' },
  { id: 'sol-heredit', bossName: 'Sol Heredit', petName: 'Smol heredit', dropRate: 200, image: '/images/projects/pets/smol-heredit.png' },
  { id: 'tempoross', bossName: 'Tempoross', petName: 'Tiny tempor', dropRate: 8000, image: '/images/projects/pets/tiny-tempor.png' },
  { id: 'theatre-of-blood', bossName: 'Theatre of Blood', petName: "Lil' zik", dropRate: 650, image: '/images/projects/pets/lil-zik.png' },
  { id: 'the-gauntlet', bossName: 'The Gauntlet', petName: 'Youngllef', dropRate: 2000, image: '/images/projects/pets/youngllef.png' },
  { id: 'the-whisperer', bossName: 'The Whisperer', petName: 'Wisp', dropRate: 2000, image: '/images/projects/pets/wisp.png' },
  { id: 'thermonuclear-smoke-devil', bossName: 'Thermonuclear Smoke Devil', petName: 'Pet smoke devil', dropRate: 3000, image: '/images/projects/pets/pet-smoke-devil.png' },
  { id: 'tombs-of-amascut', bossName: 'Tombs of Amascut', petName: "Tumeken's guardian", dropRate: 2000, image: '/images/projects/pets/tumekens-guardian.png' },
  { id: 'vardorvis', bossName: 'Vardorvis', petName: 'Butch', dropRate: 3000, image: '/images/projects/pets/butch.png' },
  { id: 'venenatis', bossName: 'Venenatis', petName: 'Venenatis spiderling', dropRate: 1500, image: '/images/projects/pets/venenatis-spiderling.png' },
  { id: 'vetion', bossName: "Vet'ion", petName: "Vet'ion jr.", dropRate: 1500, image: '/images/projects/pets/vetion-jr.png' },
  { id: 'vorkath', bossName: 'Vorkath', petName: 'Vorki', dropRate: 3000, image: '/images/projects/pets/vorki.png' },
  { id: 'wintertodt', bossName: 'Wintertodt', petName: 'Phoenix', dropRate: 5000, image: '/images/projects/pets/phoenix.png' },
  { id: 'yama', bossName: 'Yama', petName: 'Yami', dropRate: 2500, image: '/images/projects/pets/yami.png' },
  { id: 'zalcano', bossName: 'Zalcano', petName: 'Smolcano', dropRate: 2250, image: '/images/projects/pets/smolcano.png' },
  { id: 'zulrah', bossName: 'Zulrah', petName: 'Pet snakeling', dropRate: 4000, image: '/images/projects/pets/pet-snakeling.png' },
];
