const PRESETS = [
  {
    id: 'harry-potter',
    title: 'Harry Potter',
    description: 'All 8 films of the Wizarding World saga',
    category: 'Fantasy',
    totalMinutes: 1179,
    movies: [
      { id: 671, title: "Philosopher's Stone", runtime: 152 },
      { id: 672, title: 'Chamber of Secrets', runtime: 161 },
      { id: 673, title: 'Prisoner of Azkaban', runtime: 142 },
      { id: 674, title: 'Goblet of Fire', runtime: 157 },
      { id: 675, title: 'Order of the Phoenix', runtime: 138 },
      { id: 767, title: 'Half-Blood Prince', runtime: 153 },
      { id: 12444, title: 'Deathly Hallows Pt. 1', runtime: 146 },
      { id: 12445, title: 'Deathly Hallows Pt. 2', runtime: 130 },
    ],
  },
  {
    id: 'lotr',
    title: 'Lord of the Rings',
    description: 'The original trilogy — theatrical cuts',
    category: 'Fantasy',
    totalMinutes: 558,
    movies: [
      { id: 120, title: 'The Fellowship of the Ring', runtime: 178 },
      { id: 121, title: 'The Two Towers', runtime: 179 },
      { id: 122, title: 'The Return of the King', runtime: 201 },
    ],
  },
  {
    id: 'star-wars-skywalker',
    title: 'Star Wars: Skywalker Saga',
    description: 'All 9 episodes in order',
    category: 'Sci-Fi',
    totalMinutes: 1273,
    movies: [
      { id: 1893, title: 'The Phantom Menace', runtime: 136 },
      { id: 1894, title: 'Attack of the Clones', runtime: 142 },
      { id: 1895, title: 'Revenge of the Sith', runtime: 140 },
      { id: 11, title: 'A New Hope', runtime: 121 },
      { id: 1891, title: 'The Empire Strikes Back', runtime: 124 },
      { id: 1892, title: 'Return of the Jedi', runtime: 131 },
      { id: 140607, title: 'The Force Awakens', runtime: 136 },
      { id: 181808, title: 'The Last Jedi', runtime: 152 },
      { id: 181812, title: 'The Rise of Skywalker', runtime: 141 },
    ],
  },
  {
    id: 'mcu-infinity-saga',
    title: 'MCU: Infinity Saga',
    description: 'All 22 films from Iron Man to Endgame',
    category: 'Action',
    totalMinutes: 2940,
    movies: [
      { id: 1726, title: 'Iron Man', runtime: 126 },
      { id: 1724, title: 'The Incredible Hulk', runtime: 112 },
      { id: 10138, title: 'Iron Man 2', runtime: 124 },
      { id: 10195, title: 'Thor', runtime: 115 },
      { id: 1771, title: 'Captain America: The First Avenger', runtime: 124 },
      { id: 24428, title: 'The Avengers', runtime: 143 },
      { id: 68721, title: 'Iron Man 3', runtime: 130 },
      { id: 76338, title: 'Thor: The Dark World', runtime: 112 },
      { id: 100402, title: 'Captain America: The Winter Soldier', runtime: 136 },
      { id: 118340, title: 'Guardians of the Galaxy', runtime: 121 },
      { id: 99861, title: 'Avengers: Age of Ultron', runtime: 141 },
      { id: 102399, title: 'Ant-Man', runtime: 117 },
      { id: 271110, title: 'Captain America: Civil War', runtime: 147 },
      { id: 284052, title: 'Doctor Strange', runtime: 115 },
      { id: 283995, title: 'Guardians of the Galaxy Vol. 2', runtime: 136 },
      { id: 315635, title: 'Spider-Man: Homecoming', runtime: 133 },
      { id: 284053, title: 'Thor: Ragnarok', runtime: 130 },
      { id: 284054, title: 'Black Panther', runtime: 134 },
      { id: 299536, title: 'Avengers: Infinity War', runtime: 149 },
      { id: 363088, title: 'Ant-Man and the Wasp', runtime: 118 },
      { id: 299537, title: 'Captain Marvel', runtime: 124 },
      { id: 299534, title: 'Avengers: Endgame', runtime: 181 },
    ],
  },
];

export const handler = async () => {
  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Cache-Control': 'max-age=3600',
    },
    body: JSON.stringify({ success: true, presets: PRESETS }),
  };
};
