import type { Preset } from './types';

export const PRESETS: Preset[] = [
  {
    id: 'harry-potter',
    title: 'Harry Potter',
    description: 'All 8 films of the Wizarding World saga',
    category: 'Fantasy',
    totalMinutes: 1179,
    movies: [
      { id: 671, title: "Philosopher's Stone", runtime: 152 },
      { id: 672, title: 'Chamber of Secrets', runtime: 161 },
      { id: 673, title: 'Prisoner of Azkaban', runtime: 142 },
      { id: 674, title: 'Goblet of Fire', runtime: 157 },
      { id: 675, title: 'Order of the Phoenix', runtime: 138 },
      { id: 767, title: 'Half-Blood Prince', runtime: 153 },
      { id: 12444, title: 'Deathly Hallows Pt. 1', runtime: 146 },
      { id: 12445, title: 'Deathly Hallows Pt. 2', runtime: 130 },
    ],
  },
  {
    id: 'lotr',
    title: 'Lord of the Rings',
    description: 'The original trilogy — theatrical cuts',
    category: 'Fantasy',
    totalMinutes: 558,
    movies: [
      { id: 120, title: 'The Fellowship of the Ring', runtime: 178 },
      { id: 121, title: 'The Two Towers', runtime: 179 },
      { id: 122, title: 'The Return of the King', runtime: 201 },
    ],
  },
  {
    id: 'star-wars-skywalker',
    title: 'Star Wars: Skywalker Saga',
    description: 'All 9 episodes in order',
    category: 'Sci-Fi',
    totalMinutes: 1273,
    movies: [
      { id: 1893, title: 'The Phantom Menace', runtime: 136 },
      { id: 1894, title: 'Attack of the Clones', runtime: 142 },
      { id: 1895, title: 'Revenge of the Sith', runtime: 140 },
      { id: 11, title: 'A New Hope', runtime: 121 },
      { id: 1891, title: 'The Empire Strikes Back', runtime: 124 },
      { id: 1892, title: 'Return of the Jedi', runtime: 131 },
      { id: 140607, title: 'The Force Awakens', runtime: 136 },
      { id: 181808, title: 'The Last Jedi', runtime: 152 },
      { id: 181812, title: 'The Rise of Skywalker', runtime: 141 },
    ],
  },
  {
    id: 'mcu-infinity-saga',
    title: 'MCU: Infinity Saga',
    description: 'All 22 films from Iron Man to Endgame',
    category: 'Action',
    totalMinutes: 2940,
    movies: [
      { id: 1726, title: 'Iron Man', runtime: 126 },
      { id: 1724, title: 'The Incredible Hulk', runtime: 112 },
      { id: 10138, title: 'Iron Man 2', runtime: 124 },
      { id: 10195, title: 'Thor', runtime: 115 },
      { id: 1771, title: 'Captain America: The First Avenger', runtime: 124 },
      { id: 24428, title: 'The Avengers', runtime: 143 },
      { id: 68721, title: 'Iron Man 3', runtime: 130 },
      { id: 76338, title: 'Thor: The Dark World', runtime: 112 },
      { id: 100402, title: 'Captain America: The Winter Soldier', runtime: 136 },
      { id: 118340, title: 'Guardians of the Galaxy', runtime: 121 },
      { id: 99861, title: 'Avengers: Age of Ultron', runtime: 141 },
      { id: 102899, title: 'Ant-Man', runtime: 117 },
      { id: 271110, title: 'Captain America: Civil War', runtime: 147 },
      { id: 284052, title: 'Doctor Strange', runtime: 115 },
      { id: 283995, title: 'Guardians of the Galaxy Vol. 2', runtime: 136 },
      { id: 315635, title: 'Spider-Man: Homecoming', runtime: 133 },
      { id: 284053, title: 'Thor: Ragnarok', runtime: 130 },
      { id: 284054, title: 'Black Panther', runtime: 134 },
      { id: 299536, title: 'Avengers: Infinity War', runtime: 149 },
      { id: 363088, title: 'Ant-Man and the Wasp', runtime: 118 },
      { id: 299537, title: 'Captain Marvel', runtime: 124 },
      { id: 299534, title: 'Avengers: Endgame', runtime: 181 },
    ],
  },
  {
    id: 'dark-knight',
    title: 'The Dark Knight Trilogy',
    description: "Nolan's definitive Batman saga",
    category: 'Action',
    totalMinutes: 456,
    movies: [
      { id: 272, title: 'Batman Begins', runtime: 140 },
      { id: 155, title: 'The Dark Knight', runtime: 152 },
      { id: 49026, title: 'The Dark Knight Rises', runtime: 164 },
    ],
  },
  {
    id: 'indiana-jones',
    title: 'Indiana Jones',
    description: "All 5 adventures of the world's greatest archaeologist",
    category: 'Adventure',
    totalMinutes: 636,
    movies: [
      { id: 85, title: 'Raiders of the Lost Ark', runtime: 115 },
      { id: 87, title: 'Temple of Doom', runtime: 118 },
      { id: 89, title: 'The Last Crusade', runtime: 127 },
      { id: 217, title: 'Kingdom of the Crystal Skull', runtime: 122 },
      { id: 335977, title: 'Dial of Destiny', runtime: 154 },
    ],
  },
  {
    id: 'jurassic',
    title: 'Jurassic Park & World',
    description: 'All 6 films from the dinosaur franchise',
    category: 'Sci-Fi',
    totalMinutes: 747,
    movies: [
      { id: 329, title: 'Jurassic Park', runtime: 127 },
      { id: 330, title: 'The Lost World: Jurassic Park', runtime: 129 },
      { id: 331, title: 'Jurassic Park III', runtime: 92 },
      { id: 135397, title: 'Jurassic World', runtime: 124 },
      { id: 351286, title: 'Jurassic World: Fallen Kingdom', runtime: 128 },
      { id: 507086, title: 'Jurassic World Dominion', runtime: 147 },
    ],
  },
  {
    id: 'mission-impossible',
    title: 'Mission: Impossible',
    description: 'All 7 IMF missions with Ethan Hunt',
    category: 'Action',
    totalMinutes: 933,
    movies: [
      { id: 954, title: 'Mission: Impossible', runtime: 110 },
      { id: 955, title: 'M:I-2', runtime: 123 },
      { id: 956, title: 'Mission: Impossible III', runtime: 126 },
      { id: 56292, title: 'Ghost Protocol', runtime: 133 },
      { id: 177677, title: 'Rogue Nation', runtime: 131 },
      { id: 353081, title: 'Fallout', runtime: 147 },
      { id: 575264, title: 'Dead Reckoning Part One', runtime: 163 },
    ],
  },
  {
    id: 'john-wick',
    title: 'John Wick',
    description: 'All 4 chapters of the Baba Yaga saga',
    category: 'Action',
    totalMinutes: 522,
    movies: [
      { id: 245891, title: 'John Wick', runtime: 101 },
      { id: 324552, title: 'Chapter 2', runtime: 122 },
      { id: 458156, title: 'Chapter 3 – Parabellum', runtime: 130 },
      { id: 603692, title: 'Chapter 4', runtime: 169 },
    ],
  },
  {
    id: 'matrix',
    title: 'The Matrix',
    description: 'All 4 films from the Matrix universe',
    category: 'Sci-Fi',
    totalMinutes: 551,
    movies: [
      { id: 603, title: 'The Matrix', runtime: 136 },
      { id: 604, title: 'The Matrix Reloaded', runtime: 138 },
      { id: 605, title: 'The Matrix Revolutions', runtime: 129 },
      { id: 624860, title: 'The Matrix Resurrections', runtime: 148 },
    ],
  },
  {
    id: 'fast-furious',
    title: 'Fast & Furious',
    description: 'All 10 high-octane rides',
    category: 'Action',
    totalMinutes: 1246,
    movies: [
      { id: 9799, title: 'The Fast and the Furious', runtime: 106 },
      { id: 584, title: '2 Fast 2 Furious', runtime: 108 },
      { id: 9615, title: 'Tokyo Drift', runtime: 104 },
      { id: 13804, title: 'Fast & Furious', runtime: 107 },
      { id: 51497, title: 'Fast Five', runtime: 131 },
      { id: 82992, title: 'Fast & Furious 6', runtime: 130 },
      { id: 168259, title: 'Furious 7', runtime: 139 },
      { id: 337339, title: 'The Fate of the Furious', runtime: 136 },
      { id: 385128, title: 'F9', runtime: 143 },
      { id: 385687, title: 'Fast X', runtime: 142 },
    ],
  },
  {
    id: 'shrek',
    title: 'Shrek',
    description: 'All 4 layers of the beloved ogre saga',
    category: 'Animation',
    totalMinutes: 368,
    movies: [
      { id: 808, title: 'Shrek', runtime: 90 },
      { id: 809, title: 'Shrek 2', runtime: 92 },
      { id: 810, title: 'Shrek the Third', runtime: 93 },
      { id: 10192, title: 'Shrek Forever After', runtime: 93 },
    ],
  },
  {
    id: 'nolan',
    title: 'Christopher Nolan',
    description: 'Every feature from the master of mind-bending cinema',
    category: 'Director',
    totalMinutes: 1185,
    movies: [
      { id: 11660, title: 'Following', runtime: 69 },
      { id: 77, title: 'Memento', runtime: 113 },
      { id: 320, title: 'Insomnia', runtime: 118 },
      { id: 1124, title: 'The Prestige', runtime: 130 },
      { id: 27205, title: 'Inception', runtime: 148 },
      { id: 157336, title: 'Interstellar', runtime: 169 },
      { id: 374720, title: 'Dunkirk', runtime: 107 },
      { id: 577922, title: 'Tenet', runtime: 150 },
      { id: 872585, title: 'Oppenheimer', runtime: 181 },
    ],
  },
  {
    id: 'tarantino',
    title: 'Quentin Tarantino',
    description: 'All 10 films from the king of dialogue and violence',
    category: 'Director',
    totalMinutes: 1435,
    movies: [
      { id: 500, title: 'Reservoir Dogs', runtime: 99 },
      { id: 680, title: 'Pulp Fiction', runtime: 154 },
      { id: 184, title: 'Jackie Brown', runtime: 154 },
      { id: 24, title: 'Kill Bill: Vol. 1', runtime: 111 },
      { id: 393, title: 'Kill Bill: Vol. 2', runtime: 136 },
      { id: 1991, title: 'Death Proof', runtime: 113 },
      { id: 16869, title: 'Inglourious Basterds', runtime: 153 },
      { id: 68718, title: 'Django Unchained', runtime: 165 },
      { id: 273248, title: 'The Hateful Eight', runtime: 188 },
      { id: 466272, title: 'Once Upon a Time in Hollywood', runtime: 162 },
    ],
  },
  {
    id: 'villeneuve',
    title: 'Denis Villeneuve',
    description: 'The complete filmography of modern sci-fi\'s visionary',
    category: 'Director',
    totalMinutes: 1351,
    movies: [
      { id: 59482, title: 'August 32nd on Earth', runtime: 88 },
      { id: 35650, title: 'Maelstr\u00f6m', runtime: 87 },
      { id: 22302, title: 'Polytechnique', runtime: 77 },
      { id: 46738, title: 'Incendies', runtime: 131 },
      { id: 146233, title: 'Prisoners', runtime: 153 },
      { id: 181886, title: 'Enemy', runtime: 91 },
      { id: 273481, title: 'Sicario', runtime: 122 },
      { id: 329865, title: 'Arrival', runtime: 116 },
      { id: 335984, title: 'Blade Runner 2049', runtime: 164 },
      { id: 438631, title: 'Dune', runtime: 155 },
      { id: 693134, title: 'Dune: Part Two', runtime: 167 },
    ],
  },
  {
    id: 'scorsese',
    title: 'Martin Scorsese',
    description: 'All 26 narrative features from the legendary filmmaker',
    category: 'Director',
    totalMinutes: 3650,
    movies: [
      { id: 42694, title: "Who's That Knocking at My Door", runtime: 90 },
      { id: 22784, title: 'Boxcar Bertha', runtime: 88 },
      { id: 203, title: 'Mean Streets', runtime: 111 },
      { id: 16153, title: "Alice Doesn't Live Here Anymore", runtime: 112 },
      { id: 103, title: 'Taxi Driver', runtime: 114 },
      { id: 12637, title: 'New York, New York', runtime: 163 },
      { id: 1578, title: 'Raging Bull', runtime: 129 },
      { id: 262, title: 'The King of Comedy', runtime: 109 },
      { id: 10843, title: 'After Hours', runtime: 97 },
      { id: 11873, title: 'The Color of Money', runtime: 119 },
      { id: 11051, title: 'The Last Temptation of Christ', runtime: 164 },
      { id: 769, title: 'GoodFellas', runtime: 145 },
      { id: 1598, title: 'Cape Fear', runtime: 128 },
      { id: 10436, title: 'The Age of Innocence', runtime: 138 },
      { id: 524, title: 'Casino', runtime: 179 },
      { id: 9746, title: 'Kundun', runtime: 134 },
      { id: 8649, title: 'Bringing Out the Dead', runtime: 121 },
      { id: 3131, title: 'Gangs of New York', runtime: 168 },
      { id: 2567, title: 'The Aviator', runtime: 170 },
      { id: 1422, title: 'The Departed', runtime: 151 },
      { id: 11324, title: 'Shutter Island', runtime: 138 },
      { id: 44826, title: 'Hugo', runtime: 126 },
      { id: 106646, title: 'The Wolf of Wall Street', runtime: 180 },
      { id: 68730, title: 'Silence', runtime: 161 },
      { id: 398978, title: 'The Irishman', runtime: 209 },
      { id: 466420, title: 'Killers of the Flower Moon', runtime: 206 },
    ],
  },
  {
    id: 'wes-anderson',
    title: 'Wes Anderson',
    description: 'Every feature from the master of symmetry and whimsy',
    category: 'Director',
    totalMinutes: 1291,
    movies: [
      { id: 13685, title: 'Bottle Rocket', runtime: 91 },
      { id: 11545, title: 'Rushmore', runtime: 93 },
      { id: 9428, title: 'The Royal Tenenbaums', runtime: 110 },
      { id: 421, title: 'The Life Aquatic with Steve Zissou', runtime: 119 },
      { id: 4538, title: 'The Darjeeling Limited', runtime: 92 },
      { id: 10315, title: 'Fantastic Mr. Fox', runtime: 87 },
      { id: 83666, title: 'Moonrise Kingdom', runtime: 94 },
      { id: 120467, title: 'The Grand Budapest Hotel', runtime: 100 },
      { id: 399174, title: 'Isle of Dogs', runtime: 101 },
      { id: 542178, title: 'The French Dispatch', runtime: 108 },
      { id: 747188, title: 'Asteroid City', runtime: 105 },
      { id: 1259365, title: 'Henry Sugar and Three More', runtime: 89 },
      { id: 1137350, title: 'The Phoenician Scheme', runtime: 102 },
    ],
  },
  {
    id: 'fincher',
    title: 'David Fincher',
    description: 'Every feature from the dark perfectionist',
    category: 'Director',
    totalMinutes: 1621,
    movies: [
      { id: 8077, title: 'Alien\u00b3', runtime: 114 },
      { id: 807, title: 'Se7en', runtime: 127 },
      { id: 2649, title: 'The Game', runtime: 129 },
      { id: 550, title: 'Fight Club', runtime: 139 },
      { id: 4547, title: 'Panic Room', runtime: 111 },
      { id: 1949, title: 'Zodiac', runtime: 157 },
      { id: 4922, title: 'The Curious Case of Benjamin Button', runtime: 166 },
      { id: 37799, title: 'The Social Network', runtime: 121 },
      { id: 65754, title: 'The Girl with the Dragon Tattoo', runtime: 158 },
      { id: 210577, title: 'Gone Girl', runtime: 149 },
      { id: 614560, title: 'Mank', runtime: 132 },
      { id: 800158, title: 'The Killer', runtime: 118 },
    ],
  },
];
