import type { Preset } from './types';

export const PRESETS: Preset[] = [
  {
    id: 'harry-potter',
    title: 'Harry Potter',
    description: 'All 8 films of the Wizarding World saga',
    category: 'Fantasy',
    totalMinutes: 1179,
    movies: [
      { id: 671, title: "Philosopher's Stone", runtime: 152 },
      { id: 672, title: 'Chamber of Secrets', runtime: 161 },
      { id: 673, title: 'Prisoner of Azkaban', runtime: 142 },
      { id: 674, title: 'Goblet of Fire', runtime: 157 },
      { id: 675, title: 'Order of the Phoenix', runtime: 138 },
      { id: 767, title: 'Half-Blood Prince', runtime: 153 },
      { id: 12444, title: 'Deathly Hallows Pt. 1', runtime: 146 },
      { id: 12445, title: 'Deathly Hallows Pt. 2', runtime: 130 },
    ],
  },
  {
    id: 'lotr',
    title: 'Lord of the Rings',
    description: 'The original trilogy — theatrical cuts',
    category: 'Fantasy',
    totalMinutes: 558,
    movies: [
      { id: 120, title: 'The Fellowship of the Ring', runtime: 178 },
      { id: 121, title: 'The Two Towers', runtime: 179 },
      { id: 122, title: 'The Return of the King', runtime: 201 },
    ],
  },
  {
    id: 'star-wars-skywalker',
    title: 'Star Wars: Skywalker Saga',
    description: 'All 9 episodes in order',
    category: 'Sci-Fi',
    totalMinutes: 1273,
    movies: [
      { id: 1893, title: 'The Phantom Menace', runtime: 136 },
      { id: 1894, title: 'Attack of the Clones', runtime: 142 },
      { id: 1895, title: 'Revenge of the Sith', runtime: 140 },
      { id: 11, title: 'A New Hope', runtime: 121 },
      { id: 1891, title: 'The Empire Strikes Back', runtime: 124 },
      { id: 1892, title: 'Return of the Jedi', runtime: 131 },
      { id: 140607, title: 'The Force Awakens', runtime: 136 },
      { id: 181808, title: 'The Last Jedi', runtime: 152 },
      { id: 181812, title: 'The Rise of Skywalker', runtime: 141 },
    ],
  },
  {
    id: 'mcu-infinity-saga',
    title: 'MCU: Infinity Saga',
    description: 'All 22 films from Iron Man to Endgame',
    category: 'Action',
    totalMinutes: 2940,
    movies: [
      { id: 1726, title: 'Iron Man', runtime: 126 },
      { id: 1724, title: 'The Incredible Hulk', runtime: 112 },
      { id: 10138, title: 'Iron Man 2', runtime: 124 },
      { id: 10195, title: 'Thor', runtime: 115 },
      { id: 1771, title: 'Captain America: The First Avenger', runtime: 124 },
      { id: 24428, title: 'The Avengers', runtime: 143 },
      { id: 68721, title: 'Iron Man 3', runtime: 130 },
      { id: 76338, title: 'Thor: The Dark World', runtime: 112 },
      { id: 100402, title: 'Captain America: The Winter Soldier', runtime: 136 },
      { id: 118340, title: 'Guardians of the Galaxy', runtime: 121 },
      { id: 99861, title: 'Avengers: Age of Ultron', runtime: 141 },
      { id: 102399, title: 'Ant-Man', runtime: 117 },
      { id: 271110, title: 'Captain America: Civil War', runtime: 147 },
      { id: 284052, title: 'Doctor Strange', runtime: 115 },
      { id: 283995, title: 'Guardians of the Galaxy Vol. 2', runtime: 136 },
      { id: 315635, title: 'Spider-Man: Homecoming', runtime: 133 },
      { id: 284053, title: 'Thor: Ragnarok', runtime: 130 },
      { id: 284054, title: 'Black Panther', runtime: 134 },
      { id: 299536, title: 'Avengers: Infinity War', runtime: 149 },
      { id: 363088, title: 'Ant-Man and the Wasp', runtime: 118 },
      { id: 299537, title: 'Captain Marvel', runtime: 124 },
      { id: 299534, title: 'Avengers: Endgame', runtime: 181 },
    ],
  },
  {
    id: 'dark-knight',
    title: 'The Dark Knight Trilogy',
    description: "Nolan's definitive Batman saga",
    category: 'Action',
    totalMinutes: 456,
    movies: [
      { id: 272, title: 'Batman Begins', runtime: 140 },
      { id: 155, title: 'The Dark Knight', runtime: 152 },
      { id: 49026, title: 'The Dark Knight Rises', runtime: 164 },
    ],
  },
  {
    id: 'hobbit',
    title: 'The Hobbit Trilogy',
    description: 'The journey there and back again',
    category: 'Fantasy',
    totalMinutes: 474,
    movies: [
      { id: 49051, title: 'An Unexpected Journey', runtime: 169 },
      { id: 57158, title: 'The Desolation of Smaug', runtime: 161 },
      { id: 122917, title: 'The Battle of the Five Armies', runtime: 144 },
    ],
  },
  {
    id: 'indiana-jones',
    title: 'Indiana Jones',
    description: "All 5 adventures of the world's greatest archaeologist",
    category: 'Adventure',
    totalMinutes: 636,
    movies: [
      { id: 85, title: 'Raiders of the Lost Ark', runtime: 115 },
      { id: 87, title: 'Temple of Doom', runtime: 118 },
      { id: 89, title: 'The Last Crusade', runtime: 127 },
      { id: 217, title: 'Kingdom of the Crystal Skull', runtime: 122 },
      { id: 335977, title: 'Dial of Destiny', runtime: 154 },
    ],
  },
  {
    id: 'back-to-the-future',
    title: 'Back to the Future',
    description: 'The complete time-travel trilogy',
    category: 'Sci-Fi',
    totalMinutes: 342,
    movies: [
      { id: 105, title: 'Back to the Future', runtime: 116 },
      { id: 165, title: 'Back to the Future Part II', runtime: 108 },
      { id: 166, title: 'Back to the Future Part III', runtime: 118 },
    ],
  },
  {
    id: 'jurassic',
    title: 'Jurassic Park & World',
    description: 'All 6 films from the dinosaur franchise',
    category: 'Sci-Fi',
    totalMinutes: 747,
    movies: [
      { id: 329, title: 'Jurassic Park', runtime: 127 },
      { id: 330, title: 'The Lost World: Jurassic Park', runtime: 129 },
      { id: 331, title: 'Jurassic Park III', runtime: 92 },
      { id: 135397, title: 'Jurassic World', runtime: 124 },
      { id: 351286, title: 'Jurassic World: Fallen Kingdom', runtime: 128 },
      { id: 507086, title: 'Jurassic World Dominion', runtime: 147 },
    ],
  },
  {
    id: 'mission-impossible',
    title: 'Mission: Impossible',
    description: 'All 7 IMF missions with Ethan Hunt',
    category: 'Action',
    totalMinutes: 933,
    movies: [
      { id: 954, title: 'Mission: Impossible', runtime: 110 },
      { id: 955, title: 'M:I-2', runtime: 123 },
      { id: 956, title: 'Mission: Impossible III', runtime: 126 },
      { id: 56292, title: 'Ghost Protocol', runtime: 133 },
      { id: 177677, title: 'Rogue Nation', runtime: 131 },
      { id: 353081, title: 'Fallout', runtime: 147 },
      { id: 575264, title: 'Dead Reckoning Part One', runtime: 163 },
    ],
  },
  {
    id: 'john-wick',
    title: 'John Wick',
    description: 'All 4 chapters of the Baba Yaga saga',
    category: 'Action',
    totalMinutes: 522,
    movies: [
      { id: 245891, title: 'John Wick', runtime: 101 },
      { id: 393445, title: 'Chapter 2', runtime: 122 },
      { id: 458156, title: 'Chapter 3 – Parabellum', runtime: 130 },
      { id: 603692, title: 'Chapter 4', runtime: 169 },
    ],
  },
  {
    id: 'matrix',
    title: 'The Matrix',
    description: 'All 4 films from the Matrix universe',
    category: 'Sci-Fi',
    totalMinutes: 551,
    movies: [
      { id: 603, title: 'The Matrix', runtime: 136 },
      { id: 604, title: 'The Matrix Reloaded', runtime: 138 },
      { id: 605, title: 'The Matrix Revolutions', runtime: 129 },
      { id: 624860, title: 'The Matrix Resurrections', runtime: 148 },
    ],
  },
  {
    id: 'toy-story',
    title: 'Toy Story',
    description: "Pixar's beloved quadrilogy",
    category: 'Animation',
    totalMinutes: 376,
    movies: [
      { id: 862, title: 'Toy Story', runtime: 81 },
      { id: 863, title: 'Toy Story 2', runtime: 92 },
      { id: 10193, title: 'Toy Story 3', runtime: 103 },
      { id: 301528, title: 'Toy Story 4', runtime: 100 },
    ],
  },
  {
    id: 'pirates',
    title: 'Pirates of the Caribbean',
    description: 'All 5 swashbuckling adventures',
    category: 'Adventure',
    totalMinutes: 728,
    movies: [
      { id: 22, title: 'The Curse of the Black Pearl', runtime: 143 },
      { id: 58, title: "Dead Man's Chest", runtime: 151 },
      { id: 285, title: "At World's End", runtime: 168 },
      { id: 1865, title: 'On Stranger Tides', runtime: 137 },
      { id: 166426, title: 'Dead Men Tell No Tales', runtime: 129 },
    ],
  },
  {
    id: 'hunger-games',
    title: 'The Hunger Games',
    description: 'All 5 films including The Ballad of Songbirds & Snakes',
    category: 'Sci-Fi',
    totalMinutes: 705,
    movies: [
      { id: 70160, title: 'The Hunger Games', runtime: 142 },
      { id: 101299, title: 'Catching Fire', runtime: 146 },
      { id: 131631, title: 'Mockingjay Part 1', runtime: 123 },
      { id: 131634, title: 'Mockingjay Part 2', runtime: 137 },
      { id: 695721, title: 'The Ballad of Songbirds & Snakes', runtime: 157 },
    ],
  },
  {
    id: 'planet-of-the-apes',
    title: 'Planet of the Apes',
    description: 'The modern reboot trilogy plus Kingdom',
    category: 'Sci-Fi',
    totalMinutes: 520,
    movies: [
      { id: 61791, title: 'Rise of the Planet of the Apes', runtime: 105 },
      { id: 119450, title: 'Dawn of the Planet of the Apes', runtime: 130 },
      { id: 281338, title: 'War for the Planet of the Apes', runtime: 140 },
      { id: 653346, title: 'Kingdom of the Planet of the Apes', runtime: 145 },
    ],
  },
];
